version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: quick-menu-db
    restart: always
    environment:
      MYSQL_DATABASE: QuickMenu
      MYSQL_ROOT_PASSWORD: RootPassword
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: php:8.2-apache
    container_name: quick-menu-web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install mysqli &&
              a2enmod rewrite &&
              apache2-foreground"

volumes:
  mysql-volume:
    driver: local 
